mha:
  image: vvdocker/mha
  links:
    - master1:master-1
    - master2:master-2
    - slave1:slave-1
    - slave2:slave-2

master1:
  build: master
master2:
  build: slave

slave1:
  build: slave
slave2:
  build: slave
